_wandb:
    value:
        cli_version: 0.21.1
        e:
            1mmdlw05l2zwydxj4owwql5bat79x0wx:
                args:
                    - --config
                    - configs/luca_model.yaml
                codePath: train.py
                codePathLocal: train.py
                cpu_count: 4
                cpu_count_logical: 4
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "52521566208"
                        used: "29833723904"
                email: luca@wiehe.com
                executable: /home/stud/wiel/miniconda3/envs/music_recognition/bin/python
                git:
                    commit: 72f731e9564b12d0583f5030df55236780e85a64
                    remote: git@github.com:Luca-Wiehe/music_recognition.git
                gpu: NVIDIA RTX A2000 12GB
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 3328
                      memoryTotal: "12878610432"
                      name: NVIDIA RTX A2000 12GB
                      uuid: GPU-5cd95aba-2f76-7aa8-248f-755257678e34
                host: atcremers76
                memory:
                    total: "16653651968"
                os: Linux-6.14.0-28-generic-x86_64-with-glibc2.39
                program: /home/stud/wiel/music_recognition/train.py
                python: CPython 3.10.18
                root: /home/stud/wiel/music_recognition
                startedAt: "2025-08-23T10:34:33.352762Z"
                writerId: 1mmdlw05l2zwydxj4owwql5bat79x0wx
        m: []
        python_version: 3.10.18
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
            "2":
                - 1
                - 11
                - 41
                - 49
            "3":
                - 1
                - 2
                - 13
                - 15
                - 16
            "4": 3.10.18
            "5": 0.21.1
            "6": 4.55.4
            "12": 0.21.1
            "13": linux-x86_64
data:
    value:
        dataset_path: data/primus/package_aa
        num_workers: 4
        pin_memory: true
        split_ratio:
            - 0.6
            - 0.2
            - 0.2
        vocabulary_path: data/semantic_labels.txt
hardware:
    value:
        device: auto
        mixed_precision: false
logging:
    value:
        use_wandb: true
        wandb:
            notes: Music-TrOCR with ConvNeXt-Tiny backbone and transformer decoder
            project: music-recognition
            run_name: music-trocr-convnext-tiny
            tags:
                - music-trocr
                - convnext
                - transformer
                - omr
model:
    value:
        params:
            d_ff: 2048
            d_model: 512
            dropout: 0.1
            max_seq_len: 512
            n_decoder_layers: 6
            n_heads: 8
            vision_model_name: facebook/convnext-tiny-224
        type: MusicTrOCR
training:
    value:
        batch_size: 16
        checkpoint_dir: checkpoints/luca_model
        early_stop_patience: 15
        epochs: 200
        grad_clip_norm: 1
        optimizer:
            betas:
                - 0.9
                - 0.999
            learning_rate: 0.0001
            type: Adam
            weight_decay: 1e-05
        scheduler:
            cooldown: 2
            eps: 1e-08
            factor: 0.5
            mode: min
            patience: 5
            threshold: 0.0001
            threshold_mode: rel
            type: ReduceLROnPlateau
